### ISSUE TITLE
Calling conventions: short-opts, long-opts, equals, keywords, etc

### ISSUE THREAD

**Issue by stuartpb** [progrium/bashstyle#15]
I think a section on (or link to) how to parse, and *design*, script arguments, and specifically options (both long and short), would be useful.

**Comment by stuartpb** [comment]
I touched on this in #14, but I generally say you shouldn't use *environment variables* for anything that doesn't involve the script's *environment*.

One case where we definitely appear to have diverging opinions/styles is that I'm of the opinion that interfaces should be cleaved at the *script* level (and functions should only be defined as helpers *within* scripts), whereas you have things modeled at the *function* level (and treat scripts as encapsulation objects for clusters of functions). I like my way better, mostly because it doesn't force developers to write Bash in order to use your scripts.

**Comment by progrium** [comment]
Even if I was doing script file oriented Bash, I'd prefer using env for certain options. To me this is "environment". Options are a context for scripts to consider, just like environment.

But okay, this issue is on a section on designing commands.
