### ISSUE TITLE
Use `printf '%s\n'` rather than `echo` to echo strings

### ISSUE THREAD

**Issue by stuartpb** [progrium/bashstyle#18]
If the string you're echoing is `-n`, passing that string to `echo` will output **nothing**, potentially causing tons of stuff to break. This is why you should use `printf '%s\n'` for all line-echoes, except maybe when you're echoing fixed messages to STDERR with `echo >&2`.

**Comment by stuartpb** [comment]
I see this style guide as being aimed toward bulletproofing the leaky, channeling-attack-prone sieve that is Bash, and not using arguments that can be interpreted as commands is like the core tenet of that. (Normally, to avoid this hole, you'd use `--` to separate arguments, like I was showing you the other day with `set` and `ssh`, but `echo` doesn't have any such mechanism.)

**Comment by progrium** [comment]
I just don't want to rule against `echo` in the simple cases where it's obviously okay. Larger systems will probably benefit from specialized output commands, perhaps wrapping printf.

**Comment by stuartpb** [comment]
I don't rule echo out either, in the sole situation where you're specifying a complete string (with any variable substitutions coming after known static text) for human messages. Those are the only places where echo is used in Plushu.

For anywhere where a string is being echoed for technical purposes, there's no reason your function should choke on arbitrary two-character strings: all non-message output is `printf '%s\n'` (or similar) only.

**Comment by progrium** [comment]
Also if it's quoted it's not an issue. And you should quote all variables. So this is basically a non-issue.
