### ISSUE TITLE
Bash Unit Testing

### ISSUE THREAD

**Issue by sgoings** [progrium/bashstyle#2]
There's more than just shunit2 out there for bash unit testing. I've used:

- [roundup](https://github.com/bmizerany/roundup)
- plus a bunch of additions such as test reporting via junit (internal, which I'd like to get out to the community), namely better integration with:

Mocking:
- [bock](https://github.com/nwertzberger/bock)

I've also been wanting to try out:
- [bats](https://github.com/sstephenson/bats)

**Comment by progrium** [comment]
For my purposes, I don't have a reason to use anything other than shunit2 yet. I've used bats. It's ok, just a little magic.
