### ISSUE TITLE
Notes on randomness, /tmp files, cleanup, and signal traps

### ISSUE THREAD

**Issue by stuartpb** [progrium/bashstyle#21]
- When you need to save a stream, use a file created by `mktemp`. Note that mktemp will use some (crypto-strong? I don't even think so) randomness to give your file an unpredictable name that's not going to collide with anything like another concurrent running instance of your script.
  - This is the most stable and secure solution I could find: I'd be glad if someone had a better solution here, as this does kind of give me that "this is totally a hole" feeling.

- When you're making temporary files, make sure they're deleted as soon as possible.

- If you've `set -eo pipefail`, your script could exit at any point, so make sure you've got your cleanup run as part of a trap for the exit signal.

**Comment by progrium** [comment]
Can we set up a "patterns" section that captures this? It's not simple enough for a rule, but is basically the best way to do temporary files. Patterns can just have a heading ("Temporary Files"), bullet points of core points (use mktemp, delete with a trap), and an example.
