### ISSUE TITLE
Use `command -v` instead of `which` &c

### ISSUE THREAD

**Issue by stuartpb** [progrium/bashstyle#26]
`command -v` is standard and portable, `which` isn't.

**Comment by progrium** [comment]
Good point, but again, not optimizing for portability ... especially when
it is also *more* obscure / less familiar.

On Wed, Jan 14, 2015 at 6:36 PM, Stuart P. Bentley <notifications@github.com
> wrote:

> command -v is standard and portable, which isn't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/bashstyle/issues/26>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by stuartpb** [comment]
It's not just a portability concern. `which` can be broken by having another `which` in your path, which is kind of important considering that figuring out what's blocking things in your path is *what `which` is for*.

**Comment by progrium** [comment]
I just have no practical reason to be this pedantic.

**Comment by stuartpb** [comment]
> It is similar to worrying about the environment having an alias or function with the same name as a builtin, which is just as much a possibility.

Is it? I feel like builtins are handled at the lexical level, where they can't be overridden by aliases.

**Comment by progrium** [comment]
I tested overriding command with a function. So maybe not an alias but at
least functions.

On Thursday, January 15, 2015, Stuart P. Bentley <notifications@github.com>
wrote:

> It is similar to worrying about the environment having an alias or
> function with the same name as a builtin, which is just as much a
> possibility.
>
> Is it? I feel like builtins are handled at the lexical level, where they
> can't be overridden by aliases.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/bashstyle/issues/26#issuecomment-70096905>.
>


-- 
Jeff Lindsay
http://progrium.com
