### ISSUE TITLE
Throwing `set -a` and `set +a` around a variable pair list

### ISSUE THREAD

**Issue by stuartpb** [progrium/bashstyle#28]
`set -a` makes it so that every assignment has an implicit `export ` in front of it. `set +a` turns this off.

This makes it really easy to keep configuration in a file like this (which is compatible with Docker's `--env` option and `EnvironmentFile` in systemd):

```
SECRET_BASE=qweasd4321
SPECIAL_KEY=ghfdwqu98
```

and then export its variables (eg. setting up an environment for a script):

```
set -a; . config_file; set +a
```

**Comment by progrium** [comment]
More of a pro-tip than a style issue. These really aren't actionable for me, but I do encourage you to start a guide or something.

**Comment by stuartpb** [comment]
Yeah, this was the tip I was thinking of in https://github.com/progrium/bashstyle/issues/20#issuecomment-70020005
