### ISSUE TITLE
Shellcheck utility reference

### ISSUE THREAD

**Issue by sgoings** [progrium/bashstyle#3]
I've used: [ShellCheck](http://www.shellcheck.net/) in its [independently-runnable form](http://www.shellcheck.net/about.html) for a while and tie its output into a Jenkins job that shows warnings in a visible way. It might need some love, but it'd be a great to connect these "rules" with a tool that helped you understand where you're making mistakes.

**Comment by progrium** [comment]
Yeah, until we have that tool I'm not sure it's worth bringing up linters that don't check for these rules or opposing rules. Let me know if you find something more programmable!
