### ISSUE TITLE
Tracing and Debugging

### ISSUE THREAD

**Issue by stuartpb** [progrium/bashstyle#31]
One nice thing to put in a script's boilerplate is an environment variable to read that will enable xtrace and verbose, something like:

```bash
if [[ -n "$PLUSHU_TRACE" ]]; then set -vx; fi
```

This makes it possible to debug a script without having to mess with its option parsing or shebang.

**Comment by progrium** [comment]
I already have this!

On Sunday, January 18, 2015, Stuart P. Bentley <notifications@github.com>
wrote:

> One nice thing to put in a script's boilerplate is an environment variable
> to read that will enable xtrace and verbose, something like:
>
> if [[ -n "$PLUSHU_TRACE" ]]; then set -vx; fi
>
> This makes it possible to debug a script without having to mess with its
> option parsing or shebang.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/bashstyle/issues/31>.
>


-- 
Jeff Lindsay
http://progrium.com

**Comment by josegonzalez** [comment]
Close dis one :D
