### ISSUE TITLE
Example of "This can be queried/extracted with a simple function using reflection."

### ISSUE THREAD

**Issue by eedrah** [progrium/bashstyle#43]
In the section talking about `declare desc="description"`, it talks about using a function to extract this. What would this look like?

Would it be worth putting an example in the bottom section?

**Comment by czert** [comment]
There's an example in comment to a related issue: https://github.com/progrium/bashstyle/issues/36#issuecomment-274165288

**Comment by eedrah** [comment]
Thanks! I've written up a simple version of this for the README and made a pull request #44
